### ISSUE TITLE
Mapping between Elektra and KConfig

### ISSUE THREAD

**Issue by FelixResch** [ElektraInitiative/kconfig#1]
While defining a mapping from KConfig files to Elektra and back to KConfig objects, we found a few problems.

- [x] Group and key names include spaces.
- [x] File -> Key mapping
- [x] Handling of KConfig with absolute paths

## Group and key names include spaces

By splitting those names on the spaces, they can be mapped to path segments. 

One way to stay compatible is, to store meta-data about the original group and key names, so they can be represented correctly with KConfig. The backend would read this meta-data and load the correct keys into the existing KConfig structures.

Another possibility is, to re-implement KConfigGroup to use Elektra keys and translate lookups with spaces (or slashes) to subgroup lookups. With this approach no additional meta-data would be needed, but methods like `groupList` or `entryMap` would break, as they would not be able to determine which subgroups are part of the group and which are not.

A hybrid of those two would also be possible, but a lot more work.

## File -> Key mapping

Current candidate for mapping is `/sw/org/kde/<app_name>`.

## Handling of absolute paths

KConfig can also be constructed using absolute paths. As long as there is no user mounting in Elektra, I guess we should use the classic backend.

@markus2330 what are your thoughts on this

**Comment by markus2330** [comment]
Thank you for starting the discussion!

> Group and key names include spaces

I do not understand the problem. Spaces are allowed in Elektra even though we encourage not to use them.

KConfig or KConfigGroup in another KConfigGroup should be separated with `/`. Slashes given by the user in a KConfig object need to be escaped (keyAddBaseName already does this for you).

Which further information do we need to restore the KConfigGroup and KConfig?

> Current candidate for mapping is /sw/org/kde/<app_name>.

Yes `/sw/org/kde/<app_name>/<version>/<profile>`

> Handling of absolute paths

Yes, you simply write into `/sw/org/kde/<app_name>/<version>/<profile>`. It is up to the installation scripts/distributions to mount something to `/sw/org/kde/<app_name>`.

**Comment by FelixResch** [comment]
> Spaces are allowed in Elektra even though we encourage not to use them.

Then we will use spaces for the names. This way we need no extra information for the keys and don't break compatibility.

> Yes /sw/org/kde/<app_name>/<version>/<profile>

Setting `profile` will be possible using a command line switch for applications with an existing QCoreApplication or programmatically. If neither is present, `%` will be used.

How should we handle the case, when no `app_name` and `version` is present? Assuming `#0` for version seems reasonable but what about `app_name`.

> Handling of absolute paths

It is also possible to pass an absolute path to the constructor of KConfig. This is used, to open arbitrary files with the editing tools. Should we keep the file based backend, for this use-case?

**Comment by markus2330** [comment]
> Then we will use spaces for the names. This way we need no extra information for the keys and don't break compatibility.

Please give a full example of how KConfig will be mapped to KeySet. I am not sure if I fully understand. (Maybe write it already as documentation in a pullrequest)

> Setting profile will be possible using a command line switch for applications with an existing QCoreApplication or programmatically. If neither is present, % will be used.

That sounds perfect.

> How should we handle the case, when no app_name and version is present? Assuming #0 for version seems reasonable but what about app_name.

Yes, version is `#0`. Is this really possible that app_name is missing? What about assuming kglobalconfig or similar?

>  It is also possible to pass an absolute path to the constructor of KConfig. This is used, to open arbitrary files with the editing tools. Should we keep the file based backend, for this use-case?

I do not know how relevant/important this is, so I think this should get lower priority for now. Somehow the old backend needs to stay (for the desktop files).

**Comment by FelixResch** [comment]
> Please give a full example of how KConfig will be mapped to KeySet. I am not sure if I fully understand. (Maybe write it already as documentation in a pullrequest)

I will make a pull request as soon as I tried, if the mapping works. The idea would be to map the following section of e.g. `dolphinrc`

```ini
[KPropertiesDialog]
Height 1200=442
Height 1440=587
Width 2133=402
Width 2560=518
```

to the following Elektra keys

```
user/sw/org/kde/dolphin/KPropertiesDialog/Height 1200 = 442
user/sw/org/kde/dolphin/KPropertiesDialog/Height 1440 = 587
user/sw/org/kde/dolphin/KPropertiesDialog/Width 2133 = 402
user/sw/org/kde/dolphin/KPropertiesDialog/Width 2560 = 518
```

> Is this really possible that app_name is missing? What about assuming kglobalconfig or similar?

This happens, if an application that is not using the Qt Framework (and therefore not initializing the QCoreApplication values) opens a configuration with the default constructor. If globals are wanted, it would load kdeglobals and if not, an empty config with no backend is created. I wouldn't change that.

I would simply fall-back to the old backend, if an absolute path is supplied.

**Comment by markus2330** [comment]
> to the following Elektra keys

This mappings look good (except of the user:  namespace which should not be there, and version+profile is missing).

What about nested KConfigGroup?

> I would simply fall-back to the old backend, if an absolute path is supplied.

I cannot really give an answer here, I do not know the reasons why someone would do this. Anyway: if this is trivial to do, then let us do this for now. But maybe the KDE developers have different opinions about that.

**Comment by FelixResch** [comment]
> This mappings look good (except of the user: namespace which should not be there, and version+profile is missing).

Okay.

> What about nested KConfigGroup?

As far as I can tell, there is no real support for nested groups in KConfig. To support nested groups, kconfig inserts a group separator (\\x1d) into the group name. We could look for those characters and split the keys accordingly. Same goes for reconstructing.

```c++
    QByteArray fullName() const
    {
        if (!mParent) {
            return name();
        }
        return mParent->fullName(mName);
    }

    QByteArray name() const
    {
        if (mName.isEmpty()) {
            return QByteArrayLiteral("<default>");
        }
        return mName;
    }

    QByteArray fullName(const QByteArray &aGroup) const
    {
        if (mName.isEmpty()) {
            return aGroup;
        }
        return fullName() + '\x1d' + aGroup;
    }
```

This is the code, that generates subgroups. (kconfiggroup.cpp)

**Comment by markus2330** [comment]
Maybe we should translate the group separator to a /. But for a first version it will be enough to leave it as-is (especially if nobody uses nested KconfigGroup anyway).

**Comment by FelixResch** [comment]
@darddan said, he found one of those group separators in the krita config. I guess some applications use it.

Implementing it, shouldn't be much of a problem.
