### ISSUE TITLE
Recommended development environment

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/kconfig#20]
Currently I run Ubuntu Bionic (LTS) and a lot of software that I have (e.g. extra-cmake-modules and Qt5) is too old for cmake in kconfig.

Do you have any recommendations for a development environment for this repository?
Is a more recent version of Ubuntu (or a bleeding-edge distro like Arch) sufficient or do you compile all the dependencies for kconfig yourself to have the latest versions?

**Comment by markus2330** [comment]
Maybe @FelixResch can share the Image he created.

Basically, you only need to be able to compile kconfig.

But maybe it is enough if you implement it "blindly" and let @FelixResch integrate it, I think this already would help a bit.

**Comment by Chemin1** [comment]
I now have a Debian Testing VM. Here the repositories contain packages that are recent enough (except extra-cmake-modules which I compiled from source) but I just discovered that 10GB space for this VM are not enough...

@FelixResch You can find an example for how to use the new merge API in the libelektra repository in examples/kdbset.c. Additional examples are in this [pull request](https://github.com/ElektraInitiative/libelektra/pull/3260/commits).

**Comment by markus2330** [comment]
@Chemin1 as said I think it would help if you adapt your example so that it fits in kconfig. I am sure @FelixResch can make it compile afterwards if you miss some ckdb or kdb import.

**Comment by Chemin1** [comment]
I think we should continue finding solutions for merging in #19. The topic development environment of this branch is actually resolved with #21.
